name: CI

on:
  push:
    tags: v.*
    branches: master

jobs:
  release:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make all

      #- name: Test
      #  run: go test -v ./...

    - name: do release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          stream-api
          upload-proxy
          upload-server
